import { colors, fonts } from './variables';

export default {
  '--text-field-errors-color': colors.error,
  '--text-field-errors-font-family': fonts.secondary,
  '--text-field-errors-font-size': '1rem',
  '--text-field-errors-font-weight': 600,
  '--text-field-errors-line-height': '1.4rem',
  '--text-field-input-bg-color': colors.theme1,
  '--text-field-input-border': `1px solid ${colors.theme3}`,
  '--text-field-input-border-radius': '3px',
  '--text-field-input-color': colors.text1,
  '--text-field-input-font-family': colors.text1,
  '--text-field-input-font-size': '1rem',
  '--text-field-input-font-weight': 600,
  '--text-field-input-line-height': '1.4rem',
  '--text-field-input__focus-bg-color': colors.theme1,
  '--text-field-input__focus-border': `1px solid ${colors.theme3}`,
  '--text-field-input__focus-box-shadow': `0 0 0 2px ${colors.theme3}`,
  '--text-field-input__focus-color': colors.text1,
  '--text-field-label-color': colors.text1,
  '--text-field-label-font-family': fonts.secondary,
  '--text-field-label-font-size': '1rem',
  '--text-field-label-font-weight': 600,
  '--text-field-label-line-height': '1.4rem',
  '--text-field-label__focus-color': colors.primary1,
};
